import 'package:flutter/material.dart';
import 'package:flutter_mobx/flutter_mobx.dart';
import 'package:walki_admin_panel/app/utils/di/getIt.dart';
import 'package:walki_admin_panel/login/store/login_store.dart';
import 'package:walki_admin_panel/login/utils/widget/login_container.dart';

class LoginTwoFactorAuthenticationVerificationComponent extends StatefulWidget {
  const LoginTwoFactorAuthenticationVerificationComponent({super.key});

  @override
  State<LoginTwoFactorAuthenticationVerificationComponent> createState() =>
      _LoginTwoFactorAuthenticationVerificationComponentState();
}

class _LoginTwoFactorAuthenticationVerificationComponentState
    extends State<LoginTwoFactorAuthenticationVerificationComponent> {
  final _store = getIt<LoginStore>();
  late TextEditingController _controller;

  @override
  void initState() {
    super.initState();
    _controller = TextEditingController()
      ..addListener(
        () => _store.onAuthenticationCodeChanged(_controller.text),
      );
  }

  @override
  void dispose() {
    _controller.dispose();
    _store.resetAuthenticationCodeErrorMessage();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => LoginContainer(
        child: Observer(
          builder: (context) => Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const Text(
                'Two-Factor Authentication',
                style: TextStyle(
                  fontSize: 24,
                  fontWeight: FontWeight.bold,
                ),
              ),
              const SizedBox(height: 20),
              Text(
                'Enter the code generated by your authenticator app.',
                textAlign: TextAlign.center,
                style: TextStyle(
                  fontSize: 16,
                  color: Colors.grey[700],
                ),
              ),
              const SizedBox(height: 20),
              TextField(
                controller: _controller,
                decoration: InputDecoration(
                  labelText: 'Authentication Code',
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(10),
                  ),
                  errorText: _store.authenticationCodeErrorMessage,
                ),
                keyboardType: TextInputType.number,
                maxLength: 6,
              ),
              const SizedBox(height: 20),
              ElevatedButton(
                onPressed: _store.canVerifyAuthenticationCode ? _store.verifyAuthenticationCode : null,
                style: ElevatedButton.styleFrom(
                  minimumSize: const Size(double.infinity, 50),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(10),
                  ),
                ),
                child: const Text('Verify Code'),
              ),
              const SizedBox(height: 12),
              if (!_store.isAuthenticationCodeVerified)
                TextButton(
                  onPressed: _store.setupData != null
                      ? () => _store.returnToTwoFactorAuthenticationSetup(_store.setupData!)
                      : _store.returnToLoginForm,
                  child: const Text('Back'),
                )
              else ...[
                const SizedBox(height: 8),
                const Text(
                  'Code Verified! Logging you in..',
                  style: TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                    color: Colors.green,
                  ),
                ),
              ],
            ],
          ),
        ),
      );
}
